project:
  output-dir: docs

title: "قواعد كتابة الهمزة"
format:
  html:
    lang: ar
    dir: rtl
    mainfont: "Amiri"
    fontsize: 1.25rem;
    theme:
      - cosmo # body text is a little grey which is good.
      - srchtml/custom.scss
    css: srchtml/styles.css
    linkcolor: "hsl(210,10.3448275862%,47.7450980392%)" # obtained by inspecting webpage
    toc: true
    toc-title: "[الفهرست]{.aralt}"
    # background color. see also srchtml/custom.scss
    backgroundcolor: "#FDFBF7" # ultra light ivory
  typst:
    toc: false
    #toc-title: الفهرست
    lang: ar
    dir: rtl
    mainfont: "Amiri"
    linestretch: 2
    columns: 2
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf

#filters:
#  - arabic-support
#  - filters/footnotesize.lua
#  - filters/citex.lua


