## المقدمة

بسم الله الرحمن الرحيم

الحمد الله والصلاة والسلام على نبينا محمد.
أما بعد:

اعلم رحمك الله أن
<!--
الواو
تكون أحيانًا 
[صائتًا](https://ar.wikipedia.org/wiki/%D8%B5%D8%A7%D8%A6%D8%AA)
وأحيانًا 
[صامتًا](https://ar.wikipedia.org/wiki/%D8%B5%D8%A7%D9%85%D8%AA).
فمن حقها صامتًا تحرك فنقول
وَلد ووُسطى ووِلدان.
ويسكن عليها فنقول مَوْلد.
وأن الياء كذلك
صائت وشبه صامت
فمن حقها صامتًا تحرك فنقول
يَفعل ويُفعل ويسيِّر.
ويسكن عليها فنقول وَيْل.
وأن
-->
الألف
<!--
كذلك صائت وصامت.
-->
تكون أحيانًا 
[صائتًا](https://ar.wikipedia.org/wiki/%D8%B5%D8%A7%D8%A6%D8%AA)
وأحيانًا 
[صامتًا](https://ar.wikipedia.org/wiki/%D8%B5%D8%A7%D9%85%D8%AA).
وحين تكون صامتا تلفظ بصوت الهمزة.
والهمزة تحرك ويسكن عليها كما يُفعل بسائر الصوامت.
وكان حقها أن تُكتب بالألف
فذهبنا نكتب:

+ هـٰأُلاإِ (هؤلاءِ)
+ تَوْأَم (تَوْءَم)
+ خَطِيأَة (خَطِيءَة)
+ شَيْأَا (شَيْءَا)
+ سُأَال (سؤال)
+ رأس
+ بِأْسَ (بئس)
+ سُأْل (سُؤْل)

ولكن بعض القبائل أشهرها قريش كانوا لا يلفظون الهمزة إلا قليلًا.
فيبدلونها مدًّا أو حركة.
فنظنهم يقولونَ ويكتبون:

+ هـٰوُلا (هؤلاء)
+ تَوَّم (تَوْءَم)
+ خَطِيَّة (خَطِيءَة)
+ شَيَّا (شَيْءَا)
+ سُوَال (سؤال)
+ رَاس (رأس)
+ بِيسَ (بئس)
+ سُول (سُؤْل)


واتفق أن تَمَازُجًا بين كتابة لغة القريش غير المهموزة
وتلفُّظ لغات العرب المهموزة صار القياس للعربية التي كانت يكتب بها في الكتب وينطق بها في الخُطَب.
والقياس لا حرج في اقتدائه لا سيما
إذا وصّلَنا إلى تراثنا.

فشكّل الكتبة القدماء للهمزة تشكيلًا «ء» يشبه رأس العين.
وكتبوها مكانا مفتقرة إلى كرسي و في مكان مستغنية عن كرسي.
هذا بسليقة قد سُلقوها.

أما نحن فيشكل علينا.
متى نضطر الهمزة إلى كرسي فنكتبها مدعومة على الألف أو الياء أو الواو؟
ومتى نغنيها عن كرسي؟

إن توافقنا أن الكتابة القياسية هي رسم قريش شُكّل برمز الهمزة «ء»
فمذهبنا في استنباط قواعد القياس إذن
استقراء رسم قريش واستطراق تشكيلها برمز الهمزة
حتى تصلح القراءة (بالكتابة التي استنبطناها) على لغة من يهمز،
ولا تزالَ تصلح بنفس الكتابة على لغة من لم يهمز إذا حذفنا الهمزة
وربما عدلنا التشكيل الباقي.
أعني مثالا لفظة «خَطِيءَة».
إذا حذفنا همزتها وعدلنا ما بقي من التشكيل لصلحت على لغة من لا يهمز «خَطِيَّة».

فهل من كتاب صحت كتابتها كتابة قريش كي نستقرئه ونستنبط القواعد منه؟
نعم. ألا وهو المصحف الشريف.
الذي كتب بالرسم العثماني.

وهذه قواعد تبسط،
على ما وُفّقنا له،
طريقة كتابة الهمزة على أصولها بالقياس.
ونشرح بعض ما شذ منه إن شاء الله.

## الهمزة المبتدأة


أما إن كانت حركة الهمزة المبتدأة ممدودة بالألف فتكتب الهمزة مستغنية دون كرسي.
فنكتب «ءَاخِرة».
وجمع بين الهمزة والألف في غير المصحف (كما سيأتي تفصيله) وتكتب «آخرة».

وأما إن كانت حركة الهمزة غير ممدودة بألف
فتكتب الهمزة المبتدأة على الألف.
فنكتب «أَمر» و«إسلام» و«أُرِيدُ» و«أُوخِذَ» و«إِيمان».

وإن سبق الهمزةَ حرفٌ أو ما يزيد منه فيتصل بالحرف والهمزة، بقيت الهمزة على الألف.
فنكتب «بِأَمْر» و«الإسلام» و«فأُريدُ» و«الءاخرة» («الآخرة»).

وشذت من هذا القياس بضع لفظات تعاملهن كأن همزتهن متوسطة مثل «لِئَلَّا» و«لَئِنْ»
و «هؤلاء».
فلعل قريشًا قالوا «لِيَلَّا» و«لَيِنْ» و«هَـٰوُلَاء».
هؤلاء اللفظات تحفظ كتابتها كما نقلت لإثباتهن في الكتابة ولا نرى وجها لاتباع القياس فيهن.

وشذ أيضا مثل «يَبْنَؤُمَّ». فهذه وأشباهها نأخذ القياس فيها فنكتب «يا ابن أم».
وسيأتي البيان في مواقع حفظ الشواذ أو اختيار القياس في ما بعد.

## الهمزة المتوسطة

وهي أهم وأشد إشكالا.

احفظ هذه الأصول:

1. الكسر أقوى من الضم والضم أقوى من الفتح. والسكون هو الأضعف.

2. الحركة الممدودة أقوى من نفس الحركة غير الممدودة.

3. المدود «ــِي وــُو وــَا» وما يشبها «ــَوْ وــَيْ» والسكون يفضل لهن كتابة الهمزة مستغنية دون كرسي. وأما الحركات غير الممدودة فيفضل للكسر كتابة الهمزة مدعومة على كرسيها الياء،  وللضم على الواو، وللفتح على الألف.

فمن هذه الأصول نضع جدولًا للصوائت أول صفوفه لأقواها وآخر صفوفه لأضعفها:

| الصائت | الكتابة |
|-----:|-:|
|المد بالياء وشبهه «ــِي/ــَيْ» | ء |
|الكسر غير الممدود «ــِـ» | ئ |
|المد بالواو وشبهه «ــُو/ــَوْ» | ء
|الضم غير الممدود «ــُـ» | ؤ |
|المد بالألف «ــَا» | ء |
|الفتح غير الممدود «ــَـ» | أ |
|السكون «ــْـ» | ء |


وإما تستعلمن كتابة الهمزة في لفظة فاجعل الصائت الذي للهمزة والصائت الذي **قبل** الهمزة في الجدول الموضوع آنفا.
فانظر أيهما أقوى.
واكتب الهمزة كتابة الصائت الأقوى.

واعلم أيضا:

+ إن كانت الهمزة تكتب  مستغنية بدون كرسي وهي بين حرفين متواصلين
  (يعني لم يكن الحرف الأول ألفًا أو دالا أو راء أو واوا، مهملة كانت أم معجمة)
  فلا يقطع تواصلهما.
  بل تكتب الهمزة بين الحرفين الأول والآخر، فوق الخط الذي يتصل به بين الحرفين هكذا «ـءـ».
+ أن الهمزة المفتوحة المستغنية بعدها ألف (أعني «ءَا» أو «ـءَا») تكتب «آ» في غير المصحف إن كانت الألف أصلية.

لنمارس ولنر كتابة الهمزة في اللفظات:

مثالنا الأول «خَطِيءَة».
نقايِس بين الصائت الذي على الهمزة وهو الفتح والصائت قبلها وهو المد بالياء.
ننظر في الجدول أن المد بالياء أقوى وكتابتها المفضلة همزة مستغنية دون كرسي.
ونرى أن الياء قبل الهمزة يتصل بينها وبين التاء المربوطة بعدها.
فلا نقطعن وصْلهما.
فنكتب الهمزة دون كرسي فوق الخط الذي يتصل به بين الحرفين
هكذا «خَطِيءَة».

قس على ذلك واكتب
«تَوْءَم»
و«مَوْئِل»
و«مَسْءُول»
و«نَشْأَة»
و«المَرْأَة»
و«أَفْئِدَة»
و«سُؤَال»
و«سَائِل»
و«سَأَلَ»
و«سُئِلَ»
و«يَئِسَ»
و«مُطْمَئِنّ»
و«سَيِّئَة»
و«رَأْس»
و«بِئْسَ»
و«سُؤْل»
و«رُءُوس»
و«شُءُون»
و«شَنَآن»
و«ظَمْآن»
و«أُولَـٰئِكَ»
و«سَءَّال»
و«لَءَّال»
و«اسْتِيءَاس»
و«رَأَى»

وانظر في
«سَءَّال»
و«لَءَّال»
لم نجمع بين الهمزة المستغنية والألف فلم نكتب «آ». وهذا لوقوع الشَّد الذي يمنع ذلك.

وفي
«لَءَّال»
بائع اللؤلؤ،
لم نأذن للهمزة أن تقطع وصل اللام والألف الخاص «لا». فلم نكتب «لَـءَّـال» وهو خطأ.
  
و«اسْتِيءَاس»
لم نكتبها
«اسْتِيآس»
لقبح شكلها هكذا وهذا رأي منا يؤخذ أو يترك.

وأما «رَأَى» فصائت الهمزة هو الفتح الممدود ولكن بغير الألف بل بألف على صورة ياء.
فصائته الذي نجعله في الجدول هو الفتح غير الممدود الذي يساوي الصائت قبل الهمزة فتكتب الهمزة على الألف.

ولفظة «مائة» شاذة فلك فيها خيار. إما أن تكتبها كما نقلت وإما أن تكتبها «مئة» على القياس. ولا نرى بأسًا في أي منهما.



## الهمزة المتطرفة

قواعد
الهمزة المتطرفة 
مثل
قواعد
الهمزة المتوسطة
إلا لا ينظر إلى حركة الهمزة.
وإنما ينظر إلى الصائت الذي يقع قبل الهمزة.
يوضع الصائت في الجدول وتكتب الهمزة كما يشير إليه الجدول.
إليك بأمثلة:

«يَقْرَأُ»
و«بَطُؤَ»
و«متكِئ»
و«شَيْء»
و«ضَوْء»
و«سُوء»
و«سَيِّئ»
و«مبتدَأ»
و«دعاء»
و«جِيء»
و«عِبْء»

ويستثنى من القياس لفظة «تَبَوُّء» فتكتب الهمزة مستغنية لا على واو ثانية.

وإذا كتبت الهمزة المتطرفة على الألف والهمزة مكسورة فلك فيها خيار.
إما أن تكتب الهمزة تحت الألف وإما أن تكتبها فوقها. مثل
«من المَبْدَإِ» أو «من المبدأ».
ونفضل أن نكتبها فوق الألف إلا إذا شكّل بالكسرة تحت الألف.


## الهمزة المتطرفة الملحقة بمزيد

قد تكون الهمزة متطرفة أصلًا قد ألحقت بمزيد
مثل
«مَجِيءُهُ»
و«خاطِءين».

الأصل في هذه الحالات أن تحسب الهمزة متوسطة وتتبع قواعد الهمزة المتوسطة. فتكتب:

«بَرِيءُونَ»
و«بَرِيءَانِ»
و«بَرِيءِينَ»
و«بَرِيءَيْنِ»
و«سِيءَتْ»
و«شَيْءُهُ»
و«شَيْءَهُ»
و«شَيْءِهِ»
و«شَيْءَانِ»
و«شَيْءَيْنِ»
و«مَجِيءُهُ»
و«مَجِيءَهُ»
و«مَجِيءِهِ»
و«سُوئِهِ»
و«ضَوْئِهِ»
و«يَسُوءُونَ»
و«سُوءُهُ»
و«سُوءَهُ»
و«سُوءَانِ»
و«ضَوْءَهُ»
و«ضَوْءَانِ»
و«مُرْجَءَات»
و«خَاطِءِين»
و«خَاسِءِين»
و«مُتَّكِءِينَ»
و«مُتَّكِئُونَ»
و«يُبَرِّئُونَ»
و«يُبَرَّءُونَ»
و«ٱقْرَءُوا»
و«سَيِّئَات»
و«فِئَات»
و«فِئُون»
و«مِئَات»
و«مِئُون»
و«يُطْفِئُوا»
و«مُسْتَهْزِئُون»
و«مُنْشِئُون»
و«يُضَاهِئُونَ»
و«مُرْجِئُون»
و«قِرَاءَات»

انظر كيف لا تجتمع «ءَا» فتكون «آ». هذا لأن الألف في المزيد ليست أصلية.

يستثنى من الأصل الهمزة التي قبلها ساكن فتكتب مستغنية ولو وتلحق بمزيد. مثل:

«جُزْءَانِ»
و«عِبْءَانِ»
و«عِبْءَيْنِ»
و«بُطْءَهُ»
و«بُطْءُهُ»
و«بُطْءِهِ»


## الهمزة المنونة


الهمزة المنونة متطرفة
لا إشكال فيها
إلا التي تنون تنوين الفتح
فتكتب بعدها ألف (هذا إذا لم يكن قبلها المد بالألف).
فإذا كتبت بعد الهمزة المنونة ألف حسبت همزة متوسطة بعدها المد بالألف.
كأننا نقف عليها. ويوضع في الجدول الصائت الذي قبل الهمزة وصائت الهمزة،
وهو المد بالألف فينظر أيهما أقوى. كما فعلنا من قبل.

فلنأخذ «مبتدَأ» مثالا. لا مد بالألف قبل الهمزة فإذا نونّا الهمزة ألحقناها بألف.
فالصائت الذي قبل الهمزة هي حركة الدال وهو الفتح. وصائت الهمزة هو المد بالألف.
المد بالألف أقوى فتكتب الهمزة مستغنية وبعدها ألف هكذا «مبتدَءًا».

كذلك 
«شَيْءًا»
و«مَلْجَءًا»
و«جُزْءًا»
و«سَيِّئًا»
و«مِلْءًا»

## اختلافات قديمة وحديثة

القواعد التي وضعناها هي محاولة إلى كتابة قريش.
ولنا أن نقيس بها فنكتب أي لفظة شئنا.

ولكن إذا رأينا في المصحف الذي كتب بالرسم العثماني
رأينا بعض لفظات كتبت على خلاف القياس الذي وضعناه.

فنرى فيه:

|الرسم العثماني | قياسنا |
|---:|---:|
|يُضَاهِءُونَ   |يُضَاهِئُونَ   |
|مُتَّكِءُونَ    |مُتَّكِئُونَ    |
|سَيِّءَات     |سَيِّئَات     |
|يُطْفِءُوا    |يُطْفِئُوا    |
|مُرْجِءُونَ    |مُرْجِئُونَ    |
|مُسْتَهْزِءُونَ  |مُسْتَهْزِئُونَ  |
|مَالِءُونَ  |مَالِئُونَ  |

وفي كل منهن كتبت الهمزة مستغنية دون كرسي.
ونرى القراء يحقق بعضهم الهمزة في بعض هذه اللفظات في قراءاتهم ويسهل بعضهم في بعضهن.
فإذا قسنا قياسنا كتبنا الهمزات فيهن على الياء
مثل «يُضَاهِئُونَ» و«سَيِّئَات».
واطراد استغناء الهمزة عن كرسي في مثل هذه اللفظات في الرسم العثماني يدل على أنه ليس بشاذ.
أفأخطأنا في وضع قياسنا إذن؟ وما الصواب؟

<!--
الأمر أمر استواءات القياس.
فمثل هذه اللفظات في هذا الأمر كمثل «استجوب» و«استحوذ» في الصرف.
القياس في وزن «استفعل» إذا كانت عينها واوا أو ياء أن تبدل واوها أو ياؤها
ألفًا.
وشذ من القياس بعض الأفعال والوجه فيهن حفظ الشاذ.
-->

الجواب أن القياس في كتابة الهمزة محاولة إلى لغة قريش غير المهموزة لا ضير.
ولكن إذ قد اتفق أن اللغة القياسية تحقق الهمزة في القراءة
فلا نرى بأسا في انحراف يسير عن كتابة قريش
ولو اطردت،
إن سهل به قواعد القياس.
نعم هو تيسير منا ولا نلبث أن نعيب بعض التياسير كما سيأتي.
فلا أرى الأمر إلا أن من التيسير ما يسوغ ومنه ما لا يسوغ.
والتيسير في الإملاء أوسع تجاوزًا منه في النحو واللغة.
ولكن من أراد أن يلتزم بكتابة قريش التزامًا فذلك أمثل وليعدل القواعد هكذا:

إذا كانت الهمزة متطرفة أصلا تلحق بمد مزيد، فتكتب الهمزة مستغنية.

ولكن لا تفعل هذا إن كانت اللفظة منقوصة، مثل
«مِئُونَ» و«فِئُون».

وتعارض آخر: نرى في المصحف «يَسْءَم» ولو قسنا قياسنا كتبناها «يَسْأَم».
ولكن «نَشْأَة» هكذا كتبت لا «نَشْءَة».
وخلاصة الأمر أتلفظت قريش «يَسَم» أم «يَسَام»،
و«نَشَة» أم «نَشَاة» أم أثبتوا الهمزة فقالوا «نَشْأَة»؟
ولا مانع من أنهم قد اختاروا واحدة في إحداهما وأخرى في الأخرى.
والقياس يفوته الشاذ ولا حرج.
لذلك لا نرى كما قلنا بأسًا في اتباع قياسنا ولو اختلف أحيانًا هو وكتابة قريش
اختلافا يسيرا.
وهكذا في «أَفْئِدة» كتبت في المصحف «أَفْءِدة» و«يَسْأَلُونَكَ» كتبت «يَسْءَلُونَكَ» وغيرهما.

وما هو بأول تيسير
قد اتُّخذ وقبل في الإملاء.
كثر  في المصحف ما بسطت التاء المربوطة بين المضاف والمضاف إليه.
فنرى في مواضع «نعمة الله» وفي مواضع «نعمت الله».
والقياس في كتابتنا اليوم إثباتها تاء مربوطة.

ولو سألنا سائل فقال ما لكم حفظتم «لَئِن» و«لِئَلَّا» و«هؤلاء» كما نقلن واخترتم قياسكم،
لا ما اطرد به الرسم العثماني،
في مثل «أَفْئدة» و«يُضاهِئُونَ» و«سَيِّئَات»؟
أجبنا أنا حسبنا «لَئِن» و«لِئَلَّا» وأمثالهما جوامد.
وأما سائر اللفظات فتعبنا أن نحفظ ما نقل في كل منها
واستصعبنا أن نضيف إلى قواعدنا قواعد نخصها لقليل من اللفظات.
وعلى كل حال هو رأي منا ولو خالفنا أحد ما استكثرنا من المخالفة فلعل الحق معه.
ونسأل الله أن يرينا الحق حقا ويرزقنا اتباعه.
كما لو قال قائل إن مثل «يضاهءون» و«سيءات» و«أفءدة» هو القياس 
لإثباته وكثرته على ما جعلناه هو القياس ، لعجزنا أن نرد عليه.
ولو كتب أحد «أَسْءِلة» لا «أسئلة» قياسًا على «أفءدة» استصوبناه.

ودون ذلك، اختلف قياسنا والقواعد الحديثة التي وضعتها المجامع وغيرها تيسيرًا.
فبعض هذه التياسير لا نرى بأسًا كبيرا فيها
(ولو لم نر مع ذلك حاجة فيها)
مثل 
«مسؤول» دون «مسءول»
و«رَئيس» دون «رءيس».
وعلة ترخيصنا إياها هي أنك لو بدلت الهمزة بكرسيها لصلحت اللفظة أو كادت تصلح تلفُّظَ اللغة غير المهموزة.
مثلا: «مَسْوُول» و«رَيِيس».
فمن أراد أن يكتب واوين أو ياءين متتابعتين في مثل هذه اللفظات فليفعل.
والوجه عندنا اتباع القياس وترك التياسير
لا سيما إذا لم يسهل القياس بها.

ولكن بعض القواعد الحديثة نعارضها أشد معارضة.
أقبحها تحويل الهمزة المستغنية بين حرفين متواصلين  إلى همزة على كرسي يائي.
مثل «مَسْئُول» دون «مَسْءُول» و«شُئُون» دون «شُءُون» و«سَئَّال» دون «سَءَّال».
لعلهم تساهلوا من أجل ظاهر التشابه بين سن الياء المتصلة «ـئـ»
وخط الصلة بين حرفين متواصلين «ـءـ».
ولكنا لا نراه تيسيرا إذ عُقّدت به قواعد القياس
ومع ذلك لم تحتمل الكتابةُ به لغةَ من لم يهمز.
ألا ترى أنك لو بدلت الهمزة في هذا التيسّر ياءً لتبيّنت الركاكة.
انظر إلى الاضطراب في
«مَسْيُول»
و«شُيُون»
و«سيَّال» وتأمل.

وما زاد الأمر سوءًا أن معظم الخطوط الحاسوبية
لا يجيز كتابة همزة مستغنية بين حرفين متواصلين
إلا أن الهمزة تقطع تواصلهما.
فلو كتبت مثالا «خَطِيءَة» بهذه الخطوط لأصبحت «خَطِي‌ءَ‌ة».

قلما صلح خط حاسوبي في هذا الأمر.
أحسنها الخط
«[الأميري](https://github.com/aliftype/amiri)»
الذي كتبت به هذه المقالة.

وخط آخر أحسن من الأخريات خط
«[الكتاب](https://github.com/nuqayah/kitab-font)»
ولكن تضطر فيها إلى أن تكتب الهمزة فوق «تطويل».

ونسأل الله أن يوفقنا لإصلاح الأمر.

